apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-poc-v2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/rafaelvieira96/python-app-poc.git'
    targetRevision: develop
    path: charts/python-app
    helm:
      parameters:
        - name: image.repository
          value: rafaelvieira96/python-app
        - name: image.tag
          value: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
